# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image-classification.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aimage-classification.proto\x12!ai.mindslab.resnet_kotlin_armeria\".\n\x0f\x43lassifyRequest\x12\r\n\x05shape\x18\x01 \x03(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\"\x1f\n\rClassifyReply\x12\x0e\n\x06result\x18\x01 \x03(\x02\x32\x90\x01\n\x1aImageClassificationService\x12r\n\x08\x43lassify\x12\x32.ai.mindslab.resnet_kotlin_armeria.ClassifyRequest\x1a\x30.ai.mindslab.resnet_kotlin_armeria.ClassifyReply\"\x00\x42)\n\'ai.mindslab.brain.resnet_kotlin_armeriab\x06proto3')



_CLASSIFYREQUEST = DESCRIPTOR.message_types_by_name['ClassifyRequest']
_CLASSIFYREPLY = DESCRIPTOR.message_types_by_name['ClassifyReply']
ClassifyRequest = _reflection.GeneratedProtocolMessageType('ClassifyRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFYREQUEST,
  '__module__' : 'image_classification_pb2'
  # @@protoc_insertion_point(class_scope:ai.mindslab.resnet_kotlin_armeria.ClassifyRequest)
  })
_sym_db.RegisterMessage(ClassifyRequest)

ClassifyReply = _reflection.GeneratedProtocolMessageType('ClassifyReply', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFYREPLY,
  '__module__' : 'image_classification_pb2'
  # @@protoc_insertion_point(class_scope:ai.mindslab.resnet_kotlin_armeria.ClassifyReply)
  })
_sym_db.RegisterMessage(ClassifyReply)

_IMAGECLASSIFICATIONSERVICE = DESCRIPTOR.services_by_name['ImageClassificationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\'ai.mindslab.brain.resnet_kotlin_armeria'
  _CLASSIFYREQUEST._serialized_start=65
  _CLASSIFYREQUEST._serialized_end=111
  _CLASSIFYREPLY._serialized_start=113
  _CLASSIFYREPLY._serialized_end=144
  _IMAGECLASSIFICATIONSERVICE._serialized_start=147
  _IMAGECLASSIFICATIONSERVICE._serialized_end=291
# @@protoc_insertion_point(module_scope)
