# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_classification_pb2 as image__classification__pb2


class ImageClassificationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Classify = channel.unary_unary(
                '/ai.mindslab.resnet_kotlin_armeria.ImageClassificationService/Classify',
                request_serializer=image__classification__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=image__classification__pb2.ClassifyReply.FromString,
                )


class ImageClassificationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Classify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageClassificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Classify': grpc.unary_unary_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=image__classification__pb2.ClassifyRequest.FromString,
                    response_serializer=image__classification__pb2.ClassifyReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.mindslab.resnet_kotlin_armeria.ImageClassificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageClassificationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Classify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.mindslab.resnet_kotlin_armeria.ImageClassificationService/Classify',
            image__classification__pb2.ClassifyRequest.SerializeToString,
            image__classification__pb2.ClassifyReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
